float:
  angular:
  - base_args: ['@metric']
    constructor: MST_Graph2
    disabled: false
    docker_tag: ann-benchmarks-mst_graph2
    module: ann_benchmarks.algorithms.mst_graph2
    name: mst_graph2
    run_groups:
      mst_graph2_100_64_[1,1,1,1]:
        args: [{alphas: [1,1,1,1],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_100_64_1-[1,1.1,1.2,1.3]:
        args: [{alphas: [1,1.1,1.2,1.3], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_100_64_1-[1,1.2,1.3,1.4]:
        args: [{alphas: [1,1.2,1.3,1.4], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_125_32_[1,1,1,1]:
        args: [{alphas: [1,1,1,1], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_125_32_1-[1,1.1,1.2,1.3]:
        args: [{alphas: [1,1.1,1.2,1.3], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_125_32_1-[1,1.2,1.3,1.4]:
        args: [{alphas: [1,1.2,1.3,1.4], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]

  euclidean:
  - base_args: ['@metric']
    constructor: MST_Graph2
    disabled: false
    docker_tag: ann-benchmarks-mst_graph2
    module: ann_benchmarks.algorithms.mst_graph2
    name: mst_graph2
    run_groups:
      mst_graph2_100_64_[1.4,10]:
        args: [{alphas: [1.4,10],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]   
      mst_graph2_100_64_[1.5,10]:
        args: [{alphas: [1.5,10], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_100_64_[1.6,10]:
        args: [{alphas: [1.6,10], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_125_32_[1.4,10]:
        args: [{alphas: [1.4,10], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_125_32_[1.5,10]:
        args: [{alphas: [1.5,10], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph2_125_32_[1.6,10]:
        args: [{alphas: [1.6,10], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]




