float:
  angular:
  - base_args: ['@metric']
    constructor: MST_Graph2
    disabled: false
    docker_tag: ann-benchmarks-mst_graph2
    module: ann_benchmarks.algorithms.mst_graph2
    name: mst_graph2
    run_groups:
      mst_graph_100_64_[2.3,5]:
        args: [{alphas: [2.3,5],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]   
      mst_graph_100_64_[1.7,5]:
        args: [{alphas: [1.7,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_100_64_[2,5]:
        args: [{alphas: [2,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[2.3,5]:
        args: [{alphas: [2.3,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.7,5]:
        args: [{alphas: [1.7,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[2,5]:
        args: [{alphas: [2,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]

  euclidean:
  - base_args: ['@metric']
    constructor: MST_Graph2
    disabled: false
    docker_tag: ann-benchmarks-mst_graph2
    module: ann_benchmarks.algorithms.mst_graph2
    name: mst_graph2
    run_groups:
      mst_graph_100_64_[2.3,5]:
        args: [{alphas: [2.3,5],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]   
      mst_graph_100_64_[1.7,5]:
        args: [{alphas: [1.7,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_100_64_[2,5]:
        args: [{alphas: [2,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[2.3,5]:
        args: [{alphas: [2.3,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.7,5]:
        args: [{alphas: [1.7,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[2,5]:
        args: [{alphas: [2,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]




