float:
  angular:
  - base_args: ['@metric']
    constructor: DiskANN
    disabled: false
    docker_tag: ann-benchmarks-new_diskann
    module: ann_benchmarks.algorithms.new_diskann
    name: new_diskann
    run_groups:
      new_diskann_100_64_1:
        args: [{alphas: [1],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      new_diskann_100_64_1.1:
        args: [{alphas: [1.1], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      new_diskann_100_64_1.2:
        args: [{alphas: [1.2], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      new_diskann_125_32_1:
        args: [{alphas: [1], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      new_diskann_125_32_1.1:
        args: [{alphas: [1.1], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      new_diskann_125_32_1.2:
        args: [{alphas: [1.2], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]

  euclidean:
  - base_args: ['@metric']
    constructor: DiskANN
    disabled: false
    docker_tag: ann-benchmarks-new_diskann
    module: ann_benchmarks.algorithms.new_diskann
    name: new_diskann
     run_groups:
      mst_graph_100_64_[1,2]:
        args: [{alphas: [1,2],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_100_64_[1.1,2]:
        args: [{alphas: [1.1,2], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_100_64_[1.2,2]:
        args: [{alphas: [1.2,2], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1,2]:
        args: [{alphas: [1,2], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.1,2]:
        args: [{alphas: [1.1,2], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.2,2]:
        args: [{alphas: [1.2,2], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]


