float:
  angular:
  - base_args: ['@metric']
    constructor: MST_Graph
    disabled: false
    docker_tag: ann-benchmarks-mst_graph
    module: ann_benchmarks.algorithms.mst_graph
    name: mst_graph
    run_groups:
      mst_graph_100_64_[1,1.1,5]:
        args: [{alphas: [1,1.1,5],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]   
      mst_graph_100_64_[1.1,1.1,5]:
        args: [{alphas: [1.1,1.1,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_100_64_[1.2,1.1,5]:
        args: [{alphas: [1.2,1.1,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1,1.1,5]:
        args: [{alphas: [1,1.1,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.1,1.1,5]:
        args: [{alphas: [1.1,1.1,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.2,1.1,5]:
        args: [{alphas: [1.2,1.1,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_100_64_[1,1,5]:
        args: [{alphas: [1,1,5],  l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]   
      mst_graph_100_64_[1.1,1,5]:
        args: [{alphas: [1.1,1,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_100_64_[1.2,1,5]:
        args: [{alphas: [1.2,1,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1,1,5]:
        args: [{alphas: [1,1,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.1,1,5]:
        args: [{alphas: [1.1,1,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
      mst_graph_125_32_[1.2,1,5]:
        args: [{alphas: [1.2,1,5], l_build: 125, max_outdegree: 32}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
  euclidean:
  - base_args: ['@metric']
    constructor: MST_Graph
    disabled: false
    docker_tag: ann-benchmarks-mst_graph
    module: ann_benchmarks.algorithms.mst_graph
    name: mst_graph
    run_groups:
      mst_graph_100_64_[1.2,1.2,5]:
        args: [{alphas: [1.2,1.2,5], l_build: 100, max_outdegree: 64}]
        query_args: [[10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]]
   
      




